### ISSUE TITLE
Expected output in grapheme to grapheme approach

### ISSUE THREAD

**Issue by Ayushi113** [AI4Bharat/IndicMFA#1]
Hi there, 

What is the type of output we can expect with this new approach? Will I still be able to get timestamps, but they will correspond to phoneme labels will now be graphemes instead of IPA or ARPABet?

What kinds of errors do you expect in conversion?

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added a new section 'Output Format and Potential Errors' to provide information about the expected output and possible conversion errors.

You can review changes in this commit: https://github.com/jjyutm4532/AI4Bharat-IndicMFA-1/commit/1b38df9d6b572f6ff7a6483047b4655d92d3b34a.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Ananth170404** [comment]
There is a direct Grapheme-To-Grapheme mapping. So basically, the graphemes are mapped to each other along with the timestamp for each grapheme. The timestamps can be visualized in Praat or can be exported as a csv file too(Kindly look into the Official MFA Docs on how to do it)

Possible errors are mostly- In few instances, the "lack of sound" can get mapped to he previous grapheme. But with a larger train dataset, these errors have reduced.
